language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/build.sh
  - ./scripts/test.sh
notifications:
  email:
    on_success: never
    on_failure: always